### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by andrewallenbruce** [andrewallenbruce/provider#90]
- [ ] Archive vignettes
- [ ] Memoise/cache functionality
- [ ] Tests for expected column names
- [ ] Remove factors, badly written helpers
- [ ] Add general helpers (empty, null, combine, na_if_common)
